package com.safeBankAB.safebankapp.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.Date;

/*
Child entity
 */
@Data
@Entity
public class Account {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    @NotNull
    @ManyToOne //Means that there can exist many accounts for one user
    /*
        @JoinColumn simply means that our Account entity will have a foreign key column named user_id referring
        to the primary attribute id of our User entity. We can therefore see this side/entity as the owning entity.
     */
    @JoinColumn(name = "socialSecurityNumber", referencedColumnName = "socialSecurityNumber")
    private User user;

    private double accountBalance;

    @NotBlank(message = "Bank name cannot be empty")
    private String bankName;

    @NotNull
    private long accountNumber;

    @Temporal(TemporalType.DATE)
    private Date expiryDate;


    public Account () {}

    public Account(double accountBalance, String bankName) {

        /* TODO

        Implement accountnumber (autogenerated)
         */
        this.accountBalance = accountBalance;
        this.bankName = bankName;
    }

    public Account(String bankName) {

        /* TODO

        Implement accountnumber (autogenerated)
         */
        this.bankName = bankName;
    }


    @Override
    public String toString() {
        String s = "";

        s += "Account\n" + "  {\n" +
                "id:" + id + "\n" +
                "accountUsername:" + this.user.getName() + "\n" +
                "accountBalance:" + this.accountBalance + "\n" +
                "bankName:" +  this.bankName + "\n" +
                "  }\n";

        return s;

    }



}
