package com.safeBankAB.safebankapp.constantsEnumerationsAndPatterns;

public enum Status {

    BAD_ACCOUNT_REGISTRATION_INPUT,
    ACCOUNT_CREATED,
    USER_ACCOUNT_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    USER_CREATED,

    SUCCESSFUL_AUTHENTICATION,
    FAILED_AUTHENTICATION


}
