package com.safeBankAB.safebankapp.utilities;

public enum Status {

    BAD_ACCOUNT_REGISTRATION_INPUT,
    ACCOUNT_CREATED,

    ACCOUNT_NOT_FOUND,
    USER_ACCOUNT_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    USER_CREATED,
    BAD_USER_CREDENTIALS_INPUT,

    SUCCESSFUL_AUTHENTICATION,
    FAILED_AUTHENTICATION,
    UNKNOWN_ERROR


}
